### ISSUE TITLE
AP CSP Test Week - Andrew

### ISSUE THREAD

**Issue by andrewc26** [MaxVukovich/P2Lions#10]
# Game Rating System to the Game Category HTML Pages and Gaming Home Page
## Gaming Rating System { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/andrewrating.html)/[Runtime](http://70.95.177.55:8080/Max/); No Back End; [Route](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/app.py#L37-L39)}
- [x] Reformat Lions Homepage to Videogame Theme
- - [x] Gaming Background
- - [x] Incorporate [Gaming Video](https://github.com/MaxVukovich/P2Lions/blob/main/templates/home.html#L18-L20)
- - - [x] If Video Background is not able to be Completed yet, embed until able to
- [x] Game Rating System
- - [x]  Add [Tier Rating System](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/andrewrating.html#L14-L28) to game
- - [x] User Inputted Review on Adventure Games 
- - [x] Get [Game Images](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/andrewrating.html#L47-L54) and Format 
-  [x] Research CSS and different types of interactive ideas to incorporate into the project like [Image Galleries](https://www.w3schools.com/css/css_image_gallery.asp) and [Fullscreen Videos](https://www.w3schools.com/howto/howto_css_fullscreen_video.asp)
## [Ticket in Progress](https://github.com/MaxVukovich/P2Lions/issues/16)

**Comment by nathanlee27** [comment]
This is a very good ticket. It shows a new learning of the subject with the game rating system and has a lot of potential of lots of work for this week. Looks good!

**Comment by awtung** [comment]
I like the idea for the main home page so everything is nice and organized.  The game rating system will be good so users can leave feedback on each game. Maybe you could add in some sort of comment feedback as well instead of just stars.

**Comment by D1935827V** [comment]
Great ticket! very specific and I like the idea of a star ranking. It has a lot of opportunity for code implementation and should make the web page more interactive with its users for NATM

**Comment by MaxVukovich** [comment]
3/3: Good incorporation of a drag and dropping system for your games. Good idea on the videos and how you would implement them. Would you use being using an API to translate into data?
