### ISSUE TITLE
AP CSP Test Week - Ahmad

### ISSUE THREAD

**Issue by OpticStranger** [MaxVukovich/P2Lions#11]
Overall Objectives 
- - [x] Incorporate Category HTML Page using Complex HTML TYPES from W3 Resource
- -  - [x] Add Images of Games
- - -   [x] Ajax Database
- - -   [x] Incorporate Database of GPU Requirements
- - -   [x] Route the HTML Page
- - -   [x] Push code and deploy. Look into creating REST API

**Comment by awtung** [comment]
This looks very organized. Lots of good ideas and everything is laid out nice to show what is going to try and be accomplished each day. This is a good ticket.

**Comment by NoahPidding** [comment]
Very detailed and organized plan, involving dates, links and check boxes. Looks visually pleasing, and hope the website gives off the same energy / vibe that this ticket has.

**Comment by AkhileshLG** [comment]
It is very organized. You put when and what you are going to complete this week. You are also very detailed in the specific things you want to complete each day.

**Comment by anthonywilsonn** [comment]
Great job incorporating the database into your project's theme and goals. 3/3

**Comment by MaxVukovich** [comment]
3/3: Good new incorporation of an unfamiliar database option. Love the usage of this database for this part of our project and how you related it to our theme.

**Comment by OpticStranger** [comment]
Self-Grade: Finished all tasks, and created GPU requirements for Battle Royale games, incorporated database and images of games. Nice Background image. 3/3.
