### ISSUE TITLE
AP CSP Test Week - Jaideep

### ISSUE THREAD

**Issue by JaideepB1** [MaxVukovich/P2Lions#12]
- [x] Adding the Star Rating System into Game page
- [x] Adding links to the official game sites onto the Game Page

**Comment by D1935827V** [comment]
Good ticket might benefit from more specificity such as getting rid of the word assisting

**Comment by mustafasharaf04** [comment]
Sounds good so far, hopefully the ticket will be more detailed as soon as possible.
