### ISSUE TITLE
AP TEST WEEK - Anthony W

### ISSUE THREAD

**Issue by anthonywilsonn** [MaxVukovich/P2Lions#13]
Add forum for the user to decide the new game
 Add descriptions of game of the month with images
 Turn in complete Game Of The Month { Front End Code/Runtime; No Back End; Route}

**Comment by Naweid** [comment]
Nice work and good to see you guys have a plan ready.

**Comment by AkhileshLG** [comment]
Suggest you add more the ticket so there is links to the code of whatever you are working

**Comment by ghost** [comment]
Hey Anthony, nice that you guys have already completed the project. Some good things to add into the project might be add in a public discussion board somewhere to display user's comments.

**Comment by OpticStranger** [comment]
Although you did not have much info on here, I saw the work you did. I really like your game rating system. 3/3.
