### ISSUE TITLE
Final Project Week - Max

### ISSUE THREAD

**Issue by MaxVukovich** [MaxVukovich/P2Lions#15]
# Crossover API
## Crossover API: [Front End](https://github.com/MaxVukovich/P2Lions/blob/main/templates/crossover.html), [Backend](https://github.com/MaxVukovich/P2Lions/blob/main/main.py), [Route](https://github.com/MaxVukovich/P2Lions/blob/5ad4f83fc5551aa40df02b151f8e4675168258c5/main.py#L123-L131)

- [x] Use crossover api to incorporate into our own project with Game of the Month and give them our API for one of our games 

- [x] Figure out which API would be best to share and research theirs

- [x] HTML Form to display

**Comment by anthonywilsonn** [comment]
Good idea for the crossover API as it is a requirement for us.

**Comment by andrewc26** [comment]
Important ticket and good task to complete. API seems very useful, especially the video game aspect.

**Comment by OpticStranger** [comment]
Crossover API is key, which HTML will you use? Are you using postman?

**Comment by anthonywilsonn** [comment]
Thanks for the API ticket and incorporating it with the game of the month feature as this task was essential. Great job Max!

**Comment by OpticStranger** [comment]
Great job checking off a major requirement of transferring data across our crossover. 3/3
