### ISSUE TITLE
Final Project Week - Andrew

### ISSUE THREAD

**Issue by andrewc26** [MaxVukovich/P2Lions#16]
# Main Goal(s): Upcoming Video Game Page, Update Features, Progress on DB
# # Self-Grade: 3/3 Completed all work and used time wisely
# # Slideshow { [Front End Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html)/Runtime; No Back End; [Route](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/app.py#L41-L43)
- [x] Create a new page to highlight and inform user's about [new video games](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/gamescomingsoon.html) coming soon
-  [x] Create an [Automatic Slideshow](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html#L5-L71) for Adventure Games
- [x] Research New Interactive Aspects Involving DB's or Advanced CSS 
- - [x] Create interactive [pop-up](https://www.w3schools.com/howto/howto_js_popup.asp) on my homepage that returns a random gaming fact
- [x] Start Working on a Database so User's can Interact with and Give Feedback on Games

**Comment by MaxVukovich** [comment]
Good idea separating your previous ticket into this to get the videos into this, would love to see it working. Also, great implantation of another API into the project. Can't wait to see what you can do with this API

**Comment by OpticStranger** [comment]
A very good idea of incorporating the HTML with API. How are you going to accomplish this?

**Comment by anthonywilsonn** [comment]
Nice Job Andrew on the html and connecting it with the API. Great contribution to the group
