### ISSUE TITLE
Final Project Week - Anthony

### ISSUE THREAD

**Issue by anthonywilsonn** [MaxVukovich/P2Lions#17]
The ticket for the Final Project Week is to implement the deployment for our group.

**Comment by MaxVukovich** [comment]
Great idea! Backend code always needs a front end! Also Deployment is a key factor for live demo's so getting deployment working on your device and Mr. M's device is necessary.

**Comment by andrewc26** [comment]
Deployment is key factor in the project overall and a good use of time.

**Comment by MaxVukovich** [comment]
3/3: Having frontend is always necessary for backend code plus you did a great job. Also, deployment is key so getting that done works out great.
