### ISSUE TITLE
Final Project Week - Ahmad

### ISSUE THREAD

**Issue by OpticStranger** [MaxVukovich/P2Lions#19]
# Main Goal: API
# # API { [Front End Code](https://github.com/MaxVukovich/P2Lions/blob/main/templates/gom.html)/Runtime; Back End; [Route](https://github.com/MaxVukovich/P2Lions/blob/1933cc9ad5930ec280b37e670511b6e2724eaa55/main.py#L105-L120)
API Database with Game of the Month
![image](https://user-images.githubusercontent.com/72882180/121225758-b11e1b80-c83e-11eb-81d5-8ead38917480.png)

**Comment by andrewc26** [comment]
Nice job implementing an API for the game of the month since it provides great user input.

**Comment by anthonywilsonn** [comment]
Implementing the API is huge for the data and user input. Great job and great contribution!!

**Comment by MaxVukovich** [comment]
API's are a huge requirement and you got the big stuff down! Great job!

**Comment by MaxVukovich** [comment]
3/3: APIs are a massive demand and you did a great job, and you've covered the major points! Excellent work!
