### ISSUE TITLE
Digital Portfolio Week - Max

### ISSUE THREAD

**Issue by MaxVukovich** [MaxVukovich/P2Lions#3]
# Competitive Shooter HTML Category
## Competitive Shooter HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Max/templates/maxhome.html)/[Runtime](http://70.95.177.55:8080/Max/); No Back End; [Route](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/app.py#L10-L12)}
- [x] **Monday**: Research complex html types to incorporate into html page 
- - [x] Look into complex html types such as [Media Objects](https://www.w3schools.com/bootstrap4/bootstrap_media_objects.asp), [Scrollspy](https://www.w3schools.com/bootstrap4/bootstrap_scrollspy.asp), [Carousel](https://www.w3schools.com/bootstrap4/bootstrap_ref_js_carousel.asp), and [Tabs](https://www.w3schools.com/bootstrap4/bootstrap_ref_js_tab.asp)
- - [x] Have an idea about what games I am going to add
- [x] **Tuesday**: Finish Digital Portfolio's [Program Code](https://github.com/MaxVukovich/P2Lions/files/6513326/Individual.Program.Code.pdf), [Video](https://user-images.githubusercontent.com/72881842/118560903-13439f00-b71f-11eb-8cfb-258e2cee9b26.mp4), and [Write-Up](https://github.com/MaxVukovich/P2Lions/files/6520108/76WY61V1_WR.pdf)
- [x] **Wednesday**: Taking APUSH AP Exam during school
- - [x] After school, convert[ old base html file](https://github.com/MaxVukovich/P2Lions/commit/913f8ac87394940ea02ebf0dcd0ef0ac71c8c39f#diff-8ef4e7767f0b835568fc7b60c5a7061c215cb8fe15b2841fa1caa90911c32e60) into [new file](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Max/templates/maxhome.html) to store games 
- - [x] Submit Digital Portfolio final with revisions
- [x] **Thursday**: Add complex html types created from research
- - [x] Add[ descriptions of competitive shooter games](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/templates/maxhome.html#L82-L109) with [images ](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/templates/maxhome.html#L27-L80)and possible embedded game videos
- - [x] Possibly add #5 by this week or put into next week's ticket
- - [x] Turn in complete Competitive Shooter HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Max/templates/maxhome.html)/[Runtime]((http://70.95.177.55:8080/Max/)); No Back End; [Route ](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/app.py#L10-L12)}

**Comment by PedroBMedeiros** [comment]
Hey Max, just testing the comments on Issues.

**Comment by andrewc26** [comment]
> # Competitive Shooter HTML Category
> ## Self-Grade: 3/3, All requirements and links were made, Ticket itself was well done
> * [x]  **Monday**: Research complex html types to incorporate into html page
> * * [x]  Look into complex html types such as [Media Objects](https://www.w3schools.com/bootstrap4/bootstrap_media_objects.asp), [Scrollspy](https://www.w3schools.com/bootstrap4/bootstrap_scrollspy.asp), [Carousel](https://www.w3schools.com/bootstrap4/bootstrap_ref_js_carousel.asp), and [Tabs](https://www.w3schools.com/bootstrap4/bootstrap_ref_js_tab.asp)
> * * [x]  Have an idea about what games I am going to add
> * [x]  **Tuesday**: Finish Digital Portfolio's [Program Code](https://github.com/MaxVukovich/P2Lions/files/6513326/Individual.Program.Code.pdf), [Video](https://user-images.githubusercontent.com/72881842/118560903-13439f00-b71f-11eb-8cfb-258e2cee9b26.mp4), and [Write-Up](https://github.com/MaxVukovich/P2Lions/files/6520108/76WY61V1_WR.pdf)
> * [x]  **Wednesday**: Taking APUSH AP Exam during school
> * * [x]  After school, convert[ old base html file](https://github.com/MaxVukovich/P2Lions/commit/913f8ac87394940ea02ebf0dcd0ef0ac71c8c39f#diff-8ef4e7767f0b835568fc7b60c5a7061c215cb8fe15b2841fa1caa90911c32e60) into [new file](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Max/templates/maxhome.html) to store games
> * * [x]  Submit Digital Portfolio final with revisions
> * [x]  **Thursday**: Add complex html types created from research
> * * [x]  Add[ descriptions of competitive shooter games](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/templates/maxhome.html#L82-L109) with [images ](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/templates/maxhome.html#L27-L80)and possible embedded game videos
> * * [x]  Possibly add #5 by this week or put into next week's ticket
> * * [x]  Turn in complete Competitive Shooter HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Max/templates/maxhome.html)/Runtime; No Back End; [Route ](https://github.com/MaxVukovich/P2Lions/blob/2aebc511870f61c63b09caa9f6f06afde73397a7/gamereview/Max/app.py#L10-L12)}

**Comment by andrewc26** [comment]
Self-grade is justifiable and your ticket seems to be well put-together. Great job.

**Comment by andrewc26** [comment]
3/3

**Comment by jm1021** [comment]
Max, you seem to have a real gift for getting things organized.  I was impressed when you were showing me automation this week.  As far as your HTML and this type of layout it would be nice to see the page loaded from data (this type of page).  As we move into 3rd try we would like to see you dynamically add this content.  I like the detail, but I am wondering if daily should be a comment and the Ticket should have a goal.  What do you think?  3/3
