### ISSUE TITLE
Digital Portfolio Week - Andrew 

### ISSUE THREAD

**Issue by andrewc26** [MaxVukovich/P2Lions#4]
# Adventure HTML Category
## Adventure HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html)/[Runtime](http://70.95.177.55:8080/Andrew/adventuregames); No Back End; [Route ](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/app.py#L10-L12)}

- [x] **Monday**: Finish Digital Portfolio's Program Code and Written Responses
- - [x] Look into complex html/advanced CSS types such as 
[Images](https://www.w3schools.com/css/css3_images.asp), 
[Formatting](https://www.w3schools.com/html/html_formatting.asp), 
[Backgrounds](https://www.w3schools.com/css/css_background.asp), 
[Animations](https://www.w3schools.com/css/css3_animations.asp)
- - [x] Plan potential adventure games for the project
- [x] **Tuesday**: Finish Digital Portfolio's Program Code, [Video](https://user-images.githubusercontent.com/73131429/118754679-664f4c00-b81c-11eb-843b-a102d9c0cd33.mp4), and Write-Up
- [x] **Wednesday**: Work on ticket and Submit Create Task
- - [x] Create an html file for [adventure games](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html) 
- - [x] Submit Digital Portfolio final with revisions
- [x] **Thursday**: Add complex html/CSS created from research
- - [x] Add [descriptions](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html#L22-L49) of adventure games with [images](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html#L55-L103) and possible [embedded game videos](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html#L8-L12)
- - [x] Turn in complete Adventure HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/templates/adventuregames.html)/[Runtime](http://70.95.177.55:8080/Andrew/adventuregames); No Back End; [Route ](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Andrew/app.py#L10-L12)}

**Comment by MaxVukovich** [comment]
Self-grading is reasonable, and your ticket appears to be well-made. You did an excellent job.

**Comment by jm1021** [comment]
Andrew, nice page layout.  It will be interesting to see where you go from here on details and interactions.  Looking for some backend in future.  3/3
