### ISSUE TITLE
Digital Portfolio Week #3- Ahmad

### ISSUE THREAD

**Issue by OpticStranger** [MaxVukovich/P2Lions#5]
# Battle Royale Rating System
## Rating System Page { Front End [Code ](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Ahmad/templates/rating.html)/ [Runtime](http://70.95.177.55:8080/Ahmad/rating); No Back End YET; [Routing](https://github.com/MaxVukovich/P2Lions/blob/be465bd8309ebb8797c663edca50aa4e60b70f71/gamereview/Ahmad/app.py#L38-L40) }
- [x] **Monday**: Research complex html types to incorporate into html page 
- - [x] Look into complex html types such as [Drag and Drop](https://www.w3schools.com/html/html5_draganddrop.asp), [Form](https://www.w3schools.com/html/html_form_input_types.asp)
- - [x] Have an idea about what games I am going to add for Battle Royale
- [x] **Tuesday**: Begin working on [HTML Page](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Ahmad/templates/rating.html#L1): Find a star rating system ⭐ : [Github Link](https://github.com/aaronpk/rating-stars)
- [x] **Wednesday**: Incorporate [images](https://github.com/MaxVukovich/P2Lions/blob/be465bd8309ebb8797c663edca50aa4e60b70f71/gamereview/Ahmad/templates/rating.html#L44-L51) of games and drag and drop script into HTML. 
- - [x] Begin the [CSS](https://github.com/MaxVukovich/P2Lions/blob/be465bd8309ebb8797c663edca50aa4e60b70f71/gamereview/Ahmad/templates/rating.html#L6-L14) of page 
- [x] **Thursday**: Incorporate Drag and Drop with Background Image
- - [x] Include [Background Image](https://github.com/MaxVukovich/P2Lions/blob/be465bd8309ebb8797c663edca50aa4e60b70f71/gamereview/Ahmad/templates/rating.html#L52-L56) of Page
- - [x] Turn in Rating System Page { [Front End](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Ahmad/templates/rating.html#L52-L56); No Back End YET; [Routing](https://github.com/MaxVukovich/P2Lions/blob/be465bd8309ebb8797c663edca50aa4e60b70f71/gamereview/Ahmad/app.py#L38-L40) }

**Comment by MaxVukovich** [comment]
3/3 Self-grading is reasonable, and your ticket appears to be well-made. You did an excellent job.

**Comment by jm1021** [comment]
Yes, this ticket has a lot of key elements.   I was dragging the images and find it 'mind blowing' and something I will need to learn about, I saw your reference on W3.  My thought is your ticket is an example of EXCELLENCE in planning, if it had plan at the top and then daily activities toward to plan as you illustrated.  I am impressed.  3/3

**Comment by jm1021** [comment]
IMO, with drag and drop it would make more sense to me if images were at the top.  I almost missed figuring out the idea because of the layout.
