### ISSUE TITLE
Digital Portfolio Week - Anthony

### ISSUE THREAD

**Issue by MaxVukovich** [MaxVukovich/P2Lions#6]
# Game Of The Month 
## Game Of The Month { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Anthony/templates/GameOfTheMonthForm.html)/[Runtime](http://70.95.177.55:8080/Anthony/GameOfTheMonthForm); No Back End **YET**; [Route](https://github.com/MaxVukovich/P2Lions/blob/76c170720a1dac26d65103600d1cdfc22476162c/gamereview/Anthony/app.py#L14-L16)}

- [x] Finish Digital Portfolio's Program Code and Written Responses
- [x]  Look into advanced forums and figure out game description
- - [x] Have an idea about what game to add
- [x] Taking APUSH AP Exam during school
- [x] After school, create [new html file](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Anthony/templates/GameOfTheMonthForm.html)
- [x] Add [forum](https://github.com/MaxVukovich/P2Lions/blob/76c170720a1dac26d65103600d1cdfc22476162c/gamereview/Anthony/templates/GameOfTheMonthForm.html#L85-L96) for the user to decide the new game 
- - [x] Add [descriptions of game of the month](https://github.com/MaxVukovich/P2Lions/blob/76c170720a1dac26d65103600d1cdfc22476162c/gamereview/Anthony/templates/GameOfTheMonthForm.html#L35) with [images](https://github.com/MaxVukovich/P2Lions/blob/76c170720a1dac26d65103600d1cdfc22476162c/gamereview/Anthony/templates/GameOfTheMonthForm.html#L32-L81)
- - [x] Turn in complete Game Of The Month { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Anthony/templates/GameOfTheMonthForm.html)/[Runtime](http://70.95.177.55:8080/Anthony/GameOfTheMonthForm); No Back End; [Route](https://github.com/MaxVukovich/P2Lions/blob/76c170720a1dac26d65103600d1cdfc22476162c/gamereview/Anthony/app.py#L14-L16)}

**Comment by MaxVukovich** [comment]
Self-grading is reasonable, and your ticket appears to be well-made. You did an excellent job.

**Comment by jm1021** [comment]
Anthony, it is good to see how quickly you can get a page like this together.  I see input at bottom.  I am interested in where this will go next.  3/3
