### ISSUE TITLE
Digital Portfolio Week - Jaideep

### ISSUE THREAD

**Issue by MaxVukovich** [MaxVukovich/P2Lions#7]
# Racing HTML Category / Rating System
## Racing HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Jaideep/templates/jaideep.html)/[Runtime](http://70.95.177.55:8080/Jaideep/); No Back End; [Route](https://github.com/MaxVukovich/P2Lions/blob/97d74842893533761f7a01033e388cd3155dc40a/gamereview/Jaideep/app.py#L9-L11)}

- [x] Research the [best racing games](https://www.pcgamer.com/the-best-racing-games/)
- [x] Get the game descriptions and put them in [category](https://github.com/MaxVukovich/P2Lions/blob/97d74842893533761f7a01033e388cd3155dc40a/gamereview/Jaideep/templates/jaideep.html#L18-L42)
- [x] Add [images ](https://github.com/MaxVukovich/P2Lions/blob/97d74842893533761f7a01033e388cd3155dc40a/gamereview/Jaideep/templates/jaideep.html#L18-L42) for each racing game
- [x] Start [Rating System](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Jaideep/templates/Star%20Rating.html) but needs to turn in to two issues

- [x] Turn in complete Racing HTML Category { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Jaideep/templates/jaideep.html)/[Runtime](http://70.95.177.55:8080/Jaideep/); No Back End; [Route ](https://github.com/MaxVukovich/P2Lions/blob/97d74842893533761f7a01033e388cd3155dc40a/gamereview/Jaideep/app.py#L9-L11)}

**Comment by MaxVukovich** [comment]
3/3 Self-grading is reasonable, and your ticket appears to be well-made. You did an excellent job.

**Comment by jm1021** [comment]
Jaideep, it looks like you have a lot of support in getting started.  3/3

**Comment by kailamanangan16** [comment]
You've done a lot in regards to the project and it all looks really impressive. It would be nice to see more than the html in regards to the variety if things you have planned.
