### ISSUE TITLE
AP CSP Test Week - Max

### ISSUE THREAD

**Issue by MaxVukovich** [MaxVukovich/P2Lions#9]
# Introduction to Game Rating System to the Game Category HTML Pages
## Gaming Rating System { Front End [Code](https://github.com/MaxVukovich/P2Lions/blob/main/gamereview/Max/templates/maxrating.html)/[Runtime](http://70.95.177.55:8080/Max/); [Back End](https://github.com/MaxVukovich/P2Lions/blob/5b2b59c480c35d5a203c5958258ada90623c50c2/gamereview/Max/templates/maxrating.html#L7-L27); [Route](https://github.com/MaxVukovich/P2Lions/blob/5b2b59c480c35d5a203c5958258ada90623c50c2/gamereview/Max/app.py#L14-L16)}
- [x] Game Rating System
- - [x]  Add [tier rating system](https://github.com/MaxVukovich/P2Lions/blob/1e88710e56a55b5c7522edca25838b0dddce970e/gamereview/Max/templates/maxrating.html#L32-L46) to game
- - [x]  Incorporate a Rest API or Database
- - - [x] If not figured out, continue research such as usage of [cookies](https://www.w3schools.com/js/js_cookies.asp) and a [database](https://stackoverflow.com/questions/36804208/saving-html5-drag-and-drop-elements-to-db)
- - [x] Research different types of data incorporation and see if any fit for research
- - [x] Get [game images](https://github.com/MaxVukovich/P2Lions/blob/1e88710e56a55b5c7522edca25838b0dddce970e/gamereview/Max/templates/maxrating.html#L73-L80), possible add [more games](https://github.com/MaxVukovich/P2Lions/blob/1e88710e56a55b5c7522edca25838b0dddce970e/gamereview/Max/templates/maxrating.html#L73-L80) for rating

**Comment by noyah81** [comment]
This is a really focused task for this week. Remember to coordinate whether the rating system will be associated with a profile or not. Is this using data or based on customer input?

**Comment by AkhileshLG** [comment]
Noya basically told you the main stuff you need. Maybe on your ticket, be more specific on how you are applying it to the website. So that way when Mr. M is reviewing the ticket he has something detailed.

**Comment by nathanlee27** [comment]
I think this ticket is good because it shows what you want to work on this week and is focused on that. It also is an interesting concept and it shows you are progressing with your code.

**Comment by andrewc26** [comment]
It looks like you did a great job in completing your work you had planned out. The rating system looks good. Try to get the API/Database done ASAP and use your research in the project. 3/3
